import type { Model } from "../types.ts";

/** Static Gemini Web catalog; kept outside generated model data because it is session-backed. */
export const GEMINI_WEB_MODELS: Record<string, Model<"gemini-web">> = {
	"gemini-3.6-flash": {
		id: "gemini-3.6-flash",
		name: "Gemini 3.6 Flash (Web)",
		api: "gemini-web",
		provider: "gemini-web",
		baseUrl: "https://gemini.google.com",
		reasoning: false,
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1_000_000,
		maxTokens: 32_768,
	},
	"gemini-3.5-flash": {
		id: "gemini-3.5-flash",
		name: "Gemini 3.5 Flash (Web)",
		api: "gemini-web",
		provider: "gemini-web",
		baseUrl: "https://gemini.google.com",
		reasoning: false,
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1_000_000,
		maxTokens: 32_768,
	},
	"gemini-3.5-flash-thinking": {
		id: "gemini-3.5-flash-thinking",
		name: "Gemini 3.5 Flash Thinking (Web)",
		api: "gemini-web",
		provider: "gemini-web",
		baseUrl: "https://gemini.google.com",
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1_000_000,
		maxTokens: 32_768,
	},
	"gemini-3.1-pro": {
		id: "gemini-3.1-pro",
		name: "Gemini 3.1 Pro (Web)",
		api: "gemini-web",
		provider: "gemini-web",
		baseUrl: "https://gemini.google.com",
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1_000_000,
		maxTokens: 32_768,
	},
	"gemini-3.1-pro-enhanced": {
		id: "gemini-3.1-pro-enhanced",
		name: "Gemini 3.1 Pro Enhanced (Web)",
		api: "gemini-web",
		provider: "gemini-web",
		baseUrl: "https://gemini.google.com",
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1_000_000,
		maxTokens: 32_768,
	},
	"gemini-auto": {
		id: "gemini-auto",
		name: "Gemini Auto (Web)",
		api: "gemini-web",
		provider: "gemini-web",
		baseUrl: "https://gemini.google.com",
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1_000_000,
		maxTokens: 32_768,
	},
	"gemini-3.5-flash-thinking-lite": {
		id: "gemini-3.5-flash-thinking-lite",
		name: "Gemini 3.5 Flash Thinking Lite (Web)",
		api: "gemini-web",
		provider: "gemini-web",
		baseUrl: "https://gemini.google.com",
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1_000_000,
		maxTokens: 32_768,
	},
	"gemini-flash-lite": {
		id: "gemini-flash-lite",
		name: "Gemini Flash Lite (Web)",
		api: "gemini-web",
		provider: "gemini-web",
		baseUrl: "https://gemini.google.com",
		reasoning: false,
		input: ["text", "image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1_000_000,
		maxTokens: 32_768,
	},
};

export const GEMINI_WEB_MODEL_LIST = Object.values(GEMINI_WEB_MODELS);
